[source]
title = 'src-book'
licenses = ['Apache-2.0']
source_files = [
    'README.md',
    'LICENSE',
    'Cargo.toml',
    'src/main.rs',
    'src/cli.rs',
    'src/source/mod.rs',
    'src/source/author.rs',
    'src/source/providers/mod.rs',
    'src/source/providers/git_repository.rs',
    'src/sinks/mod.rs',
    'src/sinks/pdf/mod.rs',
]

[[source.authors]]
user_names = []
name = 'Kenton Hamaluik'
email = 'kenton@hamaluik.ca'
prominence = 4

[pdf]
output = 'src-book.pdf'
