[source]
title = 'src-book'
repository = '.'
licenses = ['Apache-2.0']
entrypoint = 'src/main.rs'
source_files = [
    'src/main.rs',
    'src/cli.rs',
    'src/highlight.rs',
    'src/source/author.rs',
    'src/source/commit.rs',
    'src/source/mod.rs',
    'src/sinks/pdf/imposition.rs',
    'src/sinks/pdf/mod.rs',
    'src/source/providers/git_repository.rs',
    'src/source/providers/mod.rs',
    'Cargo.lock',
    'Cargo.toml',
    'LICENSE',
    'README.md',
    'build.rs',
    'assets/syntaxes.bin',
    'assets/themes.bin',
    'assets/fonts/FiraMono-Bold.ttf',
    'assets/fonts/FiraMono-Regular.ttf',
    'assets/fonts/SourceCodePro-Bold.ttf',
    'assets/fonts/SourceCodePro-BoldIt.ttf',
    'assets/fonts/SourceCodePro-It.ttf',
    'assets/fonts/SourceCodePro-Regular.ttf',
]

[[source.authors]]
user_names = []
name = 'Kenton Hamaluik'
email = 'kenton@hamaluik.ca'
prominence = 20

[pdf]
font = 'SourceCodePro'
theme = 'GitHub'
outfile = 'src-book.pdf'
page_width_in = 5.5
page_height_in = 8.5
margin_top_in = 0.5
margin_outer_in = 0.125
margin_bottom_in = 0.25
margin_inner_in = 0.25
font_size_title_pt = 26.0
font_size_heading_pt = 19.0
font_size_subheading_pt = 10.0
font_size_body_pt = 8.0
font_size_small_pt = 6.0
booklet_outfile = 'src-book-booklet.pdf'
booklet_signature_size = 16
booklet_sheet_width_in = 11.0
booklet_sheet_height_in = 8.5
